### ISSUE TITLE
An empty application/experiment created by following the QNE instructions does not work

### ISSUE THREAD

**Issue by wkozlowski-tudelft** [QuTech-Delft/qne-adk#38]
I have followed the instructions from the QNE website to create an application and then create an experiment. The commands I ran were:
```
qne application create qkd alice bob
qne experiment create e91 qkd randstad
```

 I did NOT modify any configuration nor any source code. Once I did all that running `qne experiment run` from my experiment directory fails to complete and prints the following error:

```
{'exception': 'TimeoutExpired', 'message': 'Call to simulator timed out after 60 seconds.', 'trace': 'Traceback (most recent call last):\n  File "/home/wkozlowski/.virtualenvs/qne/bin/netqasm", line 8, in <module>\n    sys.exit(cli())\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/click/core.py", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/click/core.py", line 782, in main\n    rv = self.invoke(ctx)\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/click/core.py", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/click/core.py", line 610, in invoke\n    return callback(*args, **kwargs)\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/netqasm/runtime/cli.py", line 346, in simulate\n    simulate_application(\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/squidasm/run/multithread/simulate.py", line 89, in simulate_application\n    result = mgr.run_app(app_instance, use_app_config=use_app_config)\n  File "/home/wkozlowski/.virtualenvs/qne/lib64/python3.9/site-packages/squidasm/run/multithread/runtime_mgr.py", line 204, in run_app\n    results[name] = future.get()\n  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get\n    raise self._value\n  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker\n    result = (True, func(*args, **kwds))\nTypeError: main() got an unexpected keyword argument \'x\'\n'}
```

The issues seems to be with the app configuration in the experiment's directory. In my case `alice.yaml` and `bob.yaml` had key/value pairs for variables "x" and "y". However, the unmodified application in `app_alice.py` and `app_bob.py` does not expect `x` or `y`. The command `qne experiment run` successfully completed once I added `x` and `y` as parameters to the `main` function in both app files. I expect that removing the key/value pairs from the config files would also work.

It would be nice if the unmodified and empty default application and experiment setup just ran instead of erroring.

**Comment by QFer** [comment]
@wkozlowski-tudelft This was already fixed in the latest version. Did you use the qne-adk version from pypi or the latest from the repository?

**Comment by wkozlowski-tudelft** [comment]
I was using the pypi version

**Comment by QFer** [comment]
Solved in 0.3.0. Closing issue.
