### ISSUE TITLE
Dependency issue after installation

### ISSUE THREAD

**Issue by maxsnoodijk** [QuTech-Delft/qne-adk#86]
After following the installation steps, I get the following error after running an arbitrary QNE-ADK command: 
"pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package."

My installed pydantic version is 2.6.1, while setup.py mentions pydantic>=2.1.1 and pydantic-settings, which is the cause of this problem. After the installation, pydantic-settings was not installed automatically as per setup.py. After installing it manually, the error still occured.

Full traceback:

Traceback (most recent call last):
  File "../venv/bin/qne", line 5, in <module>
    from adk.command_list import app
  File "../venv/lib/python3.10/site-packages/adk/command_list.py", line 14, in <module>
    from adk.api.local_api import LocalApi
  File "../venv/lib/python3.10/site-packages/adk/api/local_api.py", line 18, in <module>
    from adk.settings import BASE_DIR
  File "../venv/lib/python3.10/site-packages/adk/settings.py", line 3, in <module>
    from pydantic import BaseSettings
  File "../venv/lib/python3.10/site-packages/pydantic/__init__.py", line 374, in __getattr__
    return _getattr_migration(attr_name)
  File "../venv/lib/python3.10/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.6/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.6/u/import-error

**Comment by QFer** [comment]
This is solved in version 0.4.0 currently op pypi
